"""radi pls

Revision ID: 2d64603f6fe2
Revises: c4c5b38511f0
Create Date: 2022-07-07 22:58:54.443658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d64603f6fe2'
down_revision = 'c4c5b38511f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('link', sa.String(length=120), nullable=True))
    op.drop_column('link', 'link_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('link_', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('link', 'link')
    # ### end Alembic commands ###
