"""radi pls

Revision ID: 9c601d523851
Revises: 2d64603f6fe2
Create Date: 2022-07-15 01:05:14.477663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c601d523851'
down_revision = '2d64603f6fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('pattern', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'pattern')
    # ### end Alembic commands ###
