"""radi pls

Revision ID: c4c5b38511f0
Revises: c4f0565cdf6e
Create Date: 2022-07-07 17:01:56.081328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c5b38511f0'
down_revision = 'c4f0565cdf6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('link_', sa.String(length=120), nullable=True))
    op.drop_column('link', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('link', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('link', 'link_')
    # ### end Alembic commands ###
